spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zee5appjpa
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: update
        naming:
          physical-strategy: com.zee.zee5app.utils.CustomNamingStrategy
    show-sql: true
server:
  port: 9005
  servlet:
    context-path: /api      